version: "3"
services:
  app:
    build: .
    container_name: rails
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/study_management_app
      - public-data:/study_management_app/public
      - tmp-data:/study_management_app/tmp
      - log-data:/study_management_app/log
    depends_on:
      - db
      - chrome
    environment:
      TZ: Asia/Tokyo
    ports:      
      - 3000:3000
      - 4000:4000
    stdin_open: true
    tty: true

  front:
    build: ./front
    container_name: vue
    command: npm run serve
    volumes:
      - ./front:/study_management_app_front
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true

  chrome:
    # image: selenium/standalone-chrome:latest
    image: selenium/standalone-chrome-debug:latest
    container_name: chrome
    ports:
        - 4444:4444
        - 5900:5900

  # web:    
  #   build:      
  #     context: containers/nginx
  #   container_name: nginx
  #   volumes:
  #     - public-data:/study_management_app/public
  #     - tmp-data:/study_management_app/tmp
  #   depends_on:      
  #     - app    
  #   ports:      
  #     - 80:80
    

  db:
    image: mysql:8.0.21
    container_name: mysql
    command: mysqld --skip-character-set-client-handshake --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'study_management_app_development'
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"
volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
  db-data: