version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.2'
        environment:
          RAILS_ENV: test
          DATABASE_HOST: '127.0.0.1'
      - image: circleci/mysql:8.0.21
    working_directory: ~/study_management_app/back

    steps:
      - checkout:
          path: ~/study_management_app
      - ruby/install-deps

  test:
    docker:
      - image: 'cimg/ruby:2.7.2'
        environment:
          RAILS_ENV: test
          DATABASE_HOST: '127.0.0.1'
      - image: circleci/mysql:8.0.21
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: bundle exec rails db:create
      - run:
          command: bundle exec rails db:migrate
      - ruby/rspec-test



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
