FROM ruby:2.7.2

ENV RAILS_ENV=production \
    TZ=Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y nodejs

WORKDIR /back

COPY Gemfile /back/Gemfile
COPY Gemfile.lock /back/Gemfile.lock
RUN bundle install
RUN mkdir -p /back/tmp/sockets

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]