FROM node:14.16.0-alpine

WORKDIR /front

ENV HOST=0.0.0.0 \
    PORT=8080

RUN apk update && npm install -g create-nuxt-app
COPY package.json /package.json
COPY package-lock.json /package-lock.json
RUN npm install

COPY . ./

RUN npm run build

EXPOSE ${PORT}

CMD ["npm", "run", "start"]