FROM node:14.16.0-alpine

WORKDIR /app

RUN apk update && npm install -g create-nuxt-app
COPY package.json /package.json
COPY package-lock.json /package-lock.json
RUN npm install

COPY . ./

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", "start"]